--- 
# Starting line of playbook
- name: Registre Variable capturing
  hosts: allDC localhost
  remote_user: devops
  tasks:
    - name: Install a package and test registered variable
      yum:
        name: httpd
        state: installed
      register: instl_result
    - debug: var=instl_result
